[package]
name = "scotty"
version = "0.1.0"
authors = ["Wouter Dullaert <wouter.dullaert@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/wdullaer/scotty"
description = "Creates a book from markdown files"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.31.2"
sled = "^0.29.2"
failure = "^0.1.6"
exitfailure = "^0.5.1"
fst = "^0.3.5"
fuzzy-matcher = "0.3.1"
bincode = "^1.2.0"
log = "^0.4.8"
pretty_env_logger = "^0.3.1"
directories = "^2.0.2"